"use client";

import { Sparkles, Terminal, ChevronRight, DollarSign, ArrowDown } from "lucide-react";
import type { AdvisorStrategy } from "@/lib/api-contract";

export default function AdvisorPanel({ data }: { data: AdvisorStrategy }) {
  const hasDiscount = data.premium_flag && data.suggested_discount_pct !== "none";
  const discountLabel = data.suggested_discount_pct ?? "none";
  const recommended = data.recommended_premium ?? 0;
  const original = data.original_premium ?? recommended;
  const savings = original - recommended;

  return (
    <div className="rounded-xl border border-violet-500/30 bg-violet-500/5 p-6 flex flex-col gap-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="w-3.5 h-3.5 text-violet-400" />
          <span className="text-[10px] font-mono tracking-[0.2em] text-slate-500 uppercase">
            Agent 3 · AI Premium Advisor
          </span>
        </div>
        {data.premium_flag ? (
          <span className="text-[10px] font-mono px-2.5 py-0.5 rounded-full border border-violet-500/40 text-violet-400">
            Adjustment Active
          </span>
        ) : (
          <span className="text-[10px] font-mono px-2.5 py-0.5 rounded-full border border-slate-700 text-slate-500">
            No Adjustment
          </span>
        )}
      </div>

      {/* Premium comparison */}
      {hasDiscount ? (
        <div className="grid grid-cols-3 gap-3">
          <div className="rounded-lg border border-slate-700/60 bg-slate-900/60 p-4 text-center">
            <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-2">
              Original
            </p>
            <p className="text-xl font-bold text-slate-400 tabular-nums line-through decoration-rose-500/60">
              ${original.toFixed(0)}
            </p>
          </div>

          <div className="rounded-lg border border-violet-500/30 bg-violet-500/10 p-4 text-center flex flex-col items-center justify-center">
            <ArrowDown className="w-4 h-4 text-violet-400 mb-1" />
            <p className="text-lg font-bold text-violet-300 tabular-nums">
              {discountLabel}
            </p>
            <p className="text-[10px] font-mono text-violet-400/70 mt-0.5">
              −${savings.toFixed(0)} saved
            </p>
          </div>

          <div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-4 text-center">
            <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-2">
              Recommended
            </p>
            <p className="text-xl font-bold text-emerald-400 tabular-nums">
              ${recommended.toFixed(0)}
            </p>
          </div>
        </div>
      ) : (
        <div className="rounded-lg border border-slate-700/60 bg-slate-900/60 p-4 flex items-center gap-3">
          <DollarSign className="w-5 h-5 text-emerald-400 shrink-0" />
          <div>
            <p className="text-sm text-slate-300">
              Premium holds at <span className="font-bold text-emerald-400">${original.toFixed(0)}</span>
            </p>
            <p className="text-[10px] font-mono text-slate-500 mt-0.5">
              Conversion score above activation gate — no discount needed
            </p>
          </div>
        </div>
      )}

      {/* Customer-facing message — typewriter font */}
      <div>
        <p className="text-[10px] font-mono uppercase tracking-widest text-slate-500 mb-2 flex items-center gap-1.5">
          <ChevronRight className="w-3 h-3" />
          Customer-Facing Message
        </p>
        <div className="relative rounded-xl rounded-tl-none border border-violet-500/20 bg-slate-900/80 px-4 py-3">
          <div className="absolute -top-px left-0 w-3 h-3 overflow-hidden">
            <div className="w-3 h-3 bg-violet-500/20 rounded-br-full" />
          </div>
          <p className="text-sm text-slate-200 leading-relaxed font-typewriter">
            {data.customer_facing_message || "No advisor message generated."}
          </p>
          <div className="mt-2.5 flex items-center gap-1">
            <Sparkles className="w-2.5 h-2.5 text-violet-500" />
            <span className="text-[10px] font-mono text-violet-500">
              Generated by LLM · Agent 3
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
