"use client";

import { Sparkles, ChevronRight, DollarSign, ArrowDown } from "lucide-react";
import type { AdvisorStrategy } from "@/lib/api-contract";

// ─────────────────────────────────────────────────────────────────────────────
//  AdvisorDetails — detailed premium comparison + customer message
//  Used inside StorytellingCard accordion
// ─────────────────────────────────────────────────────────────────────────────

export default function AdvisorDetails({ data }: { data: AdvisorStrategy }) {
  const hasDiscount = data.premium_flag && data.suggested_discount_pct !== "none";
  const discountLabel = data.suggested_discount_pct ?? "none";
  const recommended = data.recommended_premium ?? 0;
  const original = data.original_premium ?? recommended;
  const savings = original - recommended;

  return (
    <div className="flex flex-col gap-5">
      {/* Premium comparison */}
      {hasDiscount ? (
        <div className="grid grid-cols-3 gap-3">
          <div className="rounded-lg border border-slate-700/60 bg-slate-900/60 p-4 text-center">
            <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-2">
              Original
            </p>
            <p className="text-xl font-bold text-slate-400 tabular-nums line-through decoration-rose-500/60">
              ${original.toFixed(0)}
            </p>
          </div>

          <div className="rounded-lg border border-violet-500/30 bg-violet-500/10 p-4 text-center flex flex-col items-center justify-center">
            <ArrowDown className="w-4 h-4 text-violet-400 mb-1" />
            <p className="text-lg font-bold text-violet-300 tabular-nums">
              {discountLabel}
            </p>
            <p className="text-[10px] font-mono text-violet-400/70 mt-0.5">
              −${savings.toFixed(0)} saved
            </p>
          </div>

          <div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-4 text-center">
            <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-2">
              Recommended
            </p>
            <p className="text-xl font-bold text-emerald-400 tabular-nums">
              ${recommended.toFixed(0)}
            </p>
          </div>
        </div>
      ) : (
        <div className="rounded-lg border border-slate-700/60 bg-slate-900/60 p-4 flex items-center gap-3">
          <DollarSign className="w-5 h-5 text-emerald-400 shrink-0" />
          <div>
            <p className="text-sm text-slate-300">
              Premium holds at <span className="font-bold text-emerald-400">${original.toFixed(0)}</span>
            </p>
            <p className="text-[10px] font-mono text-slate-500 mt-0.5">
              Conversion score above activation gate — no discount needed
            </p>
          </div>
        </div>
      )}

      {/* Customer-facing message */}
      <div>
        <p className="text-[10px] font-mono uppercase tracking-widest text-slate-500 mb-2 flex items-center gap-1.5">
          <ChevronRight className="w-3 h-3" />
          Customer-Facing Message
        </p>
        <div className="relative rounded-xl rounded-tl-none border border-violet-500/20 bg-slate-900/80 px-4 py-3">
          <div className="absolute -top-px left-0 w-3 h-3 overflow-hidden">
            <div className="w-3 h-3 bg-violet-500/20 rounded-br-full" />
          </div>
          <p className="text-sm text-slate-200 leading-relaxed font-typewriter">
            {data.customer_facing_message || "No advisor message generated."}
          </p>
          <div className="mt-2.5 flex items-center gap-1">
            <Sparkles className="w-2.5 h-2.5 text-violet-500" />
            <span className="text-[10px] font-mono text-violet-500">
              Generated by LLM · Agent 3
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
//  Helper: derive verdict + summary from advisor data
// ─────────────────────────────────────────────────────────────────────────────
export function getAdvisorVerdict(data: AdvisorStrategy) {
  const hasDiscount = data.premium_flag && data.suggested_discount_pct !== "none";
  const recommended = data.recommended_premium ?? 0;
  const original = data.original_premium ?? recommended;

  if (hasDiscount) {
    const savings = original - recommended;
    return {
      verdict: {
        label: `${data.suggested_discount_pct} Discount`,
        variant: "info" as const,
      },
      summary: `Premium reduced from $${original.toFixed(0)} to $${recommended.toFixed(0)} (saving $${savings.toFixed(0)}) to improve conversion chances.`,
    };
  }

  return {
    verdict: {
      label: "No Adjustment",
      variant: "neutral" as const,
    },
    summary: `Premium holds at $${original.toFixed(0)}. Conversion score is strong enough — no discount is needed.`,
  };
}
